name: release

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/setup

      - name: publish
        id: changesets
        uses: changesets/action@v1
        with:
          title: version packages
          commit: version packages
          version: pnpm ci:version

          # https://github.com/changesets/action/issues/246
          # https://github.com/changesets/changesets/pull/674
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
